repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black
        types: [python]

      # - id: flake8
      #   name: flake8
      #   stages: [commit]
      #   language: system
      #   entry: pipenv run flake8
      #   types: [python]
      #   exclude: setup.py

      - id: pyright
        name: pyright
        stages: [commit]
        language: system
        entry: pipenv run pyright --lib -p pyrightconfig.json --stats

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pipenv run python -m pytest
        types: [python]
        pass_filenames: false

      - id: pytest-cov
        name: pytest
        stages: [push]
        language: system
        entry: pipenv run python -m pytest --cov --cov-fail-under=80
        types: [python]
        pass_filenames: false
